### PR TITLE
making the readme ##contributing section true to life again

### PR DESCRIPTION
**Pull request by BlueHotDog**
pretty simple PR :)

### CODE REVIEW

**Comment by thangngoc89** [comment]
I can see that you're accidentally changed a lot of files. Could you please remove them first?

**Comment by BlueHotDog** [comment]
just the package locks, whats the method of maintaining them? i just run npm install.. if there are special steps we need to document them,

**Comment by jaredly** [comment]
arg I wish npm didn't modify package locks :( :( :(

**Comment by jaredly** [comment]
thanks for helping out!

**Pull request merged**
