### PR TITLE
[example-project] add build command “genFlow” to simulate genFlow output

### PR DESCRIPTION
**Pull request by cristianoc**
Reference: https://github.com/jaredly/reason-language-server/issues/88#issuecomment-415979579.

To simulate `genFlow` output in `example-project`:
```
yarn clean
yarn genFlow
```

Happy to also generate different output if it helps parsing.

### CODE REVIEW

**Comment by cristianoc** [comment]
@jaredly I've added a command `yarn genFlow` to set up the environment variable for genFlow output for cli compilation.
To get the output picked up in vscode, the environment variable needs to be set up when vscode runs. E.g.
```
cd example-project
export BS_CMT_POST_PROCESS_CMD=$PWD/genFlowOutput.sh
code .
```

**Comment by jaredly** [comment]
ahh gotcha. Seems like it would probably be nicer to have a config option in reason-language-server to set that internally, so people don't have to mess starting vscode in a special way.
And if we do that, then this command would *only* get run when I run `bsb` internally, and not when I'm running `bsc` for per-file diagnostics.

**Comment by cristianoc** [comment]
This was intended to just run once to get an idea of how the output looks.
Consider this low pri, in case other output could be mis-interpreted in future.
I’m planning to move genFlow output to a log file anyway.

**Comment by cristianoc** [comment]
genFlow now uses a log file. Closing this as it's now just for reference.

**Pull request closed without merging**
