### PR TITLE
Add "build_system_override_by_root" config option

### LINKED ISSUE #194: "Could not find local build dir" when a dune file is present (in addition to bsb-native).
This started happening since version 1.3.0 on [genType](https://github.com/cristianoc/genType).
The project is normally built using bsb-native, but it's also buildable with dune, so it has a couple of dune files.
If the dune files are removed, all is well.

### PR DESCRIPTION
**Pull request by jaredly**
This will allow users to manually override the build system when
inference isn't cutting it.

Fixes #194

### CODE REVIEW

**Comment by jaredly** [comment]
@bsansouci do you want to try this out with bsb-native stuff?

**Comment by bsansouci** [comment]
Sure! So this is a static setting one would set inside their editor right? Is there any way to make it project specific?

**Comment by jaredly** [comment]
Yup! Vscode allows per-project config. you can do it from within vscode, or edit `<project>/.vscode/settings.json` directly

**Comment by tcoopman** [comment]
Any updates on this?

**Pull request merged**
