### PR TITLE
Add support for OCaml 4.09

### PR DESCRIPTION
**Pull request by anmonteiro**
This diff adds support for OCaml 4.09. 

The most invasive changes relates to `TypedTreeIter` not being available anymore in OCaml 4.09, so I replaced its usage in 4.09 with `Tast_iterator` ([relevant PR](https://github.com/ocaml/ocaml/pull/8539)).

There was another little change that leaked over the earlier version typing files, related to [this PR](https://github.com/ocaml/ocaml/pull/2262), which shouldn't be of too much concern.

### CODE REVIEW

**Comment by cristianoc** [comment]
@anmonteiro curious about `ocaml_typing`: are parts of the compiler checked in?
Never looked at this part of code, and was expecting`Tast_mapper` plus any compiler-version-specific code using it would be enough.

**Comment by anmonteiro** [comment]
@cristianoc to support earlier versions of the compiler, we check in the relevant files from those earlier versions -- this script lists those files: https://github.com/jaredly/reason-language-server/blob/master/ocaml_typing/assemble.js

Unlike Merlin which you have to compile for the compiler version you intend to support, Jared made the choice of distributing one prebuilt binary which has code to support all these different compiler versions.

**Comment by anmonteiro** [comment]
To clarify: to support 4.09 (i.e. the version we build RLS with) we can just use the 4.09 compiler libs, but in this case we check in the files from 4.08 which is the OCaml version we were previously compiling against.

**Comment by cristianoc** [comment]
@anmonteiro so there are multiple versions of the AST checked is, to build a single executable.
Vs building one executable per version and not checking them it.
And this is the tradeoff, correct?

**Comment by anmonteiro** [comment]
I think that's the tradeoff here, yes

**Comment by adamsmd** [comment]
Does this pull request handle the change to error message formats that was introduced in OCaml 4.09 as described in issue #309?  (See ocaml/ocaml#8541 for the actual change to OCaml.)

**Comment by imbsky** [comment]
Any updates on this?

**Comment by imbsky** [comment]
I had a quick look at all the code, but it doesn't seem like a big problem.

**Comment by cristianoc** [comment]
Please note the breakage here first: https://github.com/jaredly/reason-language-server/pull/363.
Then this needs rebasing and testins.

**Comment by anmonteiro** [comment]
I'm not interested in pursuing this PR anymore, so feel free to close.

**Comment by jfrolich** [comment]
Would be nice to have this, as I found 4.09 is not working at the moment (`graphql_ppx` just upgraded from 4.06 to 4.09). Not sure how far this PR is, but many kudos from me if anyone would pick this up 🏅 😍

**Pull request closed without merging**
