### PR TITLE
[WIP] Azure pipelines

### PR DESCRIPTION
**Pull request by ulrikstrid**
Started working on porting the CI flow to use Azure Pipelines.

I hit some error in the build I think https://strid.visualstudio.com/OSS/_build/results?buildId=275 it shows as green in the logs but there is no output in the build folder and the logs doesn't look like they should.

### CODE REVIEW

**Comment by bryphe** [comment]
Sweet, thanks @ulrikstrid !

> I hit some error in the build I think https://strid.visualstudio.com/OSS/_build/results?buildId=275 it shows as green in the logs but there is no output in the build folder and the logs doesn't look like they should.

I think with `esy@0.4.3` the build artifacts don't end up in the `_esy/default/build/...` folder anymore - they're in the store. Unfortunately we don't know this path until build - we have to use like `esy x which Bin.exe` to find it.

I'm working around this for now by setting `buildsInSource: "_build"` so that the bits end up in the predictable `_build/default/...` path, but I know that's not the ideal solution - I'm sure @andreypopp has a better solution.

**Comment by ulrikstrid** [comment]
I think I tried setting that as well, unfortunately the build fails locally on my windows machine. I could try building it on my Mac to figure out paths.

**Comment by ulrikstrid** [comment]
Used `esy x which Bin` to get the path but it still can't find it for the artifact.

https://strid.visualstudio.com/OSS/_build/results?buildId=281

**Comment by ulrikstrid** [comment]
@kaylangan it would be really nice to have a task that runs a script and saves the output as a variable
```
- script: |
     echo '##vso[task.setvariable variable=binPath]'$(esy x which Bin)
   displayName: "Save binPath variable" 
```
Could be more readable, but is not a blocker

**Comment by jaredly** [comment]
Thanks for an excellent head start! I finally got this working in #307 😅

**Pull request closed without merging**
