### PR TITLE
Upgrade ci to use latest from hello-reason

### PR DESCRIPTION
**Pull request by jchavarri**
Upgrades CI files to use the latest setup which includes Azure recently added [Cache task](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#using-the-cache-task). This removes a lot of manual handling and complexity around esy cache.

- Announcement: https://azure.microsoft.com/en-us/updates/new-deployment-strategies-and-caching-for-azure-pipelines/
- https://github.com/microsoft/azure-pipelines-tasks/blob/c9c4827c8d0951c98a9468d83db708c593c7c428/Tasks/CacheV2/task.json
- https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#using-the-cache-task

### CODE REVIEW

**Comment by jchavarri** [comment]
@jaredly there seems to be [some permissions issue](https://jaredly.visualstudio.com/reason-language-server/_build/results?buildId=128):

```
tar: could not chdir to '/Users/runner/runners/2.160.1/work/1/cache'

Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session f834923b-097f-4c7d-a958-c0c6379a4371
##[error]Process returned non-zero exit code: 1
```

I'm not sure what could be causing this, this command is part of the internal Cache saving scripts.

I thought it could be that I'm a contributor and there is some security issues, but in `hello-reason` I activated Azure cache in a PR like here and everything seemed to work: https://github.com/esy-ocaml/hello-reason/pull/53.

 @jordwalke @ulrikstrid have you run into this issue before?

**Comment by jordwalke** [comment]
I've never seen that issue before.

**Comment by jchavarri** [comment]
@jordwalke this is embarrasing, it seems I forgot to add `- template: utils/publish-build-cache.yml` 😅  Trying again now, but the `chdir` error now makes more sense (the folder did not exist).

**Comment by jaredly** [comment]
Sounds good to me!

**Pull request merged**
