### PR TITLE
Make client/registerCapability a request

### PR DESCRIPTION
**Pull request by prometheansacrifice**

### CODE REVIEW

**Comment by jaredly** [comment]
hmmm what does this do?

**Comment by prometheansacrifice** [comment]
I think the `client/registerCapability` is supposed to be a request not a notification (apologies for my incorrect commit message). 

> Register Capability
The client/registerCapability request is sent from the server to the client to register for a new capability on the client side.

[Source](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#client_registerCapability)

This will make this [emacs related PR](https://github.com/jaredly/reason-language-server/pull/308/files) unnecessary too.

**Comment by jaredly** [comment]
Gotcha, makes sense! Does this mean it's ready to merge? (it's currently in draft state)

**Comment by prometheansacrifice** [comment]
Let me me also update the README

**Comment by jaredly** [comment]
perfect!

**Comment by jaredly** [comment]
I had to revert this because it broke vscode. For some reason vscode doesn't expect registerCapability to be a request

**Comment by prometheansacrifice** [comment]
Very unfortunate. Sorry I missed this. 

Interestingly, [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node/blob/c7216c9df48786cf2e04cc2dd669a13a14cc42ad/protocol/src/protocol.ts#L142-L148), itself declares it to be a request.

**Comment by prometheansacrifice** [comment]
@jaredly What was the issue? So, I packaged the extension and ran the vsix in my vscode, and it seems to run fine.

**Pull request merged**
