### PR TITLE
 Fix PPX flags only for bsb-native (fixes #278)

### LINKED ISSUE #278: bsc is invoked with incorrect ppx path when using ppx in a non-native project
In a project that uses Bucklescript for JS compilation and a PPX (specifically https://github.com/ryb73/ppx_decco) I get a top-level error for every file:
`sh: <project-root>/lib/bs/native/ppx_decco.native: No such file or directory`

Offending bsc flag from the debug log:
`-ppx '<project-root>/lib/bs/native/ppx_decco.native'`

I think this is because we convert ppx paths for every build system, although it should be a workaround for bsb-native only:
https://github.com/jaredly/reason-language-server/blob/master/util/MerlinFile.re#L22
Called from here:
https://github.com/jaredly/reason-language-server/blob/master/util/MerlinFile.re#L435

I tried running the extension locally and was able to work around it by doing the following:
1. skip calling `fixPpx`. Now it still failed with the following (from debug log):
`sh: ppx_decco: command not found`
2. Change `ppx-flags` from "ppx_decco" to "@ryb73/decco/ppx/ppx_decco.sh"
(`ppx_decco` is a node script residing in node_modules/.bin which spawns the actual ppx, maybe the extension doesn't work with bin scripts?)

Reproduction:
1. Create a new project with `bsb -init my-new-project -theme basic-reason`
2. Run `npm i @ryb73/decco`
3. Modify `bsconfig.json` as described here:
https://github.com/ryb73/ppx_decco#how-do-i-install-it
4. Open VS Code

Environment:
OS: Mac OSX
bs-platform: 5.0.2
Extension version: 1.6.0
Settings:
```
{
  "reason_language_server.per_value_codelens": true,
  "reason_language_server.autoRebuild": false,
  "reason_language_server.show_debug_errors": true,
  "reason_language_server.useOldDuneProcess": false
}
```

### PR DESCRIPTION
**Pull request by ohana54**
1. I initially tried to detect the build system in `MerlinFile.re` so I won't have to change its interface, but `BuildSystem.re` actually depends on it, which would cause a cyclic dependency. I opted instead to pass a flag to MerlinFile functions (not sure it's the best thing to do)
2. I didn't have to check for `node_modules/.bin` and modify the path, looks like `bsc` is already working correctly for bin files.

### CODE REVIEW

**Comment by ohana54** [comment]
Hi, I did the formatting on a different commit so it can be reviewed separately, is that good enough?

**Comment by jaredly** [comment]
oh cool, yeah I think that will work

**Comment by ohana54** [comment]
Friendly reminder for review, let me know if there's anything I need to do :)

**Comment by jaredly** [comment]
i just merged in the 4.08 pr, and now this has conflicts due to the formatting changes. I'll try to find time to go in and resolve them, if you don't get to it in the next couple days

**Comment by ohana54** [comment]
I'll just remove the formatting commit and rebase on master, will update in the following days

**Comment by ohana54** [comment]
Rebased, ready again for review :)

**Comment by jaredly** [comment]
Hmm it doesn't look like that fixes it?
image

**Comment by ohana54** [comment]
It worked a few months ago, but so much has changed so anything can happen :)
I'll take a look. Thanks for not forgetting this one!

**Comment by ohana54** [comment]
Couldn't get this to work locally for some reason, and since there were changes in that area on master + the original issue is not longer valid (the ppx that had the issue was changed) I'm closing this.

**Pull request closed without merging**
